name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Create package.json for build script
        run: |
          cat > package.json << 'EOF'
          {
            "name": "felixsii-portfolio",
            "type": "module"
          }
          EOF
          
      - name: Build site (generate HTML pages from JSON)
        run: |
          cat > build-site.js << 'EOF'
          import fs from 'fs';
          
          const artworksData = JSON.parse(fs.readFileSync('static/data/artworks.json', 'utf8'));
          
          artworksData.forEach(artwork => {
              const html = \`<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Felix Siivonen - \${artwork.title}</title>
              <link rel="icon" href="static/favicon.svg">
              <script src="https://cdn.tailwindcss.com"></script>
              <script>
                  tailwind.config = {
                      theme: {
                          extend: {
                              maxWidth: {
                                  '8xl': '88rem',
                              },
                              gridTemplateColumns: {
                                  '20': 'repeat(20, minmax(0, 1fr))',
                              },
                              fontFamily: {
                                  'sans': ['TikTok Sans', 'sans-serif'],
                              }
                          }
                      }
                  }
              </script>
              <link rel="preconnect" href="https://fonts.googleapis.com">
              <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
              <link href="https://fonts.googleapis.com/css2?family=TikTok+Sans:opsz,wght@12..36,300..900&display=swap" rel="stylesheet">
          </head>
          <body>
              <!-- Navigation -->
              <nav class="bg-white">
                  <div class="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
                      <div class="flex justify-between items-center h-20">
                          <!-- Name -->
                          <div class="flex-shrink-0">
                              <a href="index.html" class="text-xl font-light tracking-wide text-gray-900">
                                  Felix Siivonen
                              </a>
                          </div>
                          
                          <!-- Desktop Navigation -->
                          <div class="hidden md:block">
                              <div class="flex items-center space-x-12 pr-3">
                                  <a href="index.html" class="text-xl font-light tracking-wide text-gray-600 hover:text-gray-900">
                                      Works
                                  </a>
                                  <a href="about.html" class="text-xl font-light tracking-wide text-gray-600 hover:text-gray-900">
                                      About
                                  </a>
                              </div>
                          </div>
                          
                          <!-- Mobile menu button -->
                          <div class="md:hidden">
                              <button id="mobile-menu-button" class="p-2 text-gray-600 hover:text-gray-900">
                                  <span class="sr-only">Open menu</span>
                                  <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 6h16M4 12h16M4 18h16" />
                                  </svg>
                              </button>
                          </div>
                      </div>
                  </div>

                  <!-- Mobile menu -->
                  <div id="mobile-menu" class="hidden md:hidden border-t border-gray-100">
                      <div class="px-3 py-4 space-y-4">
                          <a href="index.html" class="block text-xl font-light tracking-wide text-gray-600 hover:text-gray-900">
                              Works
                          </a>
                          <a href="about.html" class="block text-xl font-light tracking-wide text-gray-600 hover:text-gray-900">
                              About
                          </a>
                      </div>
                  </div>
              </nav>

              <!-- Main Content -->
              <main class="py-12">
                  <div class="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-20 gap-2">
                      <!-- Navigation Column - Back Arrow (very thin) -->
                      <div class="lg:col-span-1 flex items-start justify-start lg:justify-left pt-1 pb-4">
                          <a href="index.html" class="text-gray-600 cursor-pointer" aria-label="Go back to works">
                              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                              </svg>
                          </a>
                      </div>
                      
                      <!-- Artwork Details Column -->
                      <div class="lg:col-span-4 pr-8 pb-5">
                          <h1 class="text-2xl font-light tracking-wide text-gray-900 mb-4">
                              \${artwork.title}
                          </h1>
                          
                          <div class="text-xl font-light tracking-wide text-gray-600 space-y-2">
                              <p>\${artwork.year}</p>
                              <p>\${artwork.materials}</p>
                              <p>\${artwork.dimensions}</p>
                          </div>
                          
                          \${artwork.description ? \`<div class="mt-6 text-lg font-light tracking-wide text-gray-700 leading-relaxed">\${artwork.description}</div>\` : ''}
                      </div>
                      
                      <!-- Images Column -->
                      <div class="lg:col-span-12" style="grid-column: span 15 / span 15;">
                          <!-- Nested Grid for Images -->
                          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                              \${artwork.images.map(image => \`
                              <div class="lg:col-span-\${image.span}">
                                  <img 
                                      src="static\${image.src}"
                                      alt="\${image.alt}"
                                      class="w-full h-full object-cover rounded-lg"
                                      loading="lazy"
                                  />
                              </div>
                              \`).join('')}
                          </div>
                      </div>
                  </div>
              </main>

              <script>
                  // Mobile menu toggle
                  const mobileMenuButton = document.getElementById('mobile-menu-button');
                  const mobileMenu = document.getElementById('mobile-menu');
                  let isMenuOpen = false;

                  mobileMenuButton.addEventListener('click', () => {
                      isMenuOpen = !isMenuOpen;
                      mobileMenu.classList.toggle('hidden');
                      
                      // Update button icon
                      const svg = mobileMenuButton.querySelector('svg');

                      if (isMenuOpen) {
                          svg.innerHTML = '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M6 6l12 12" />';
                      } else {
                          svg.innerHTML = '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 6h16M4 12h16M4 18h16" />';
                      }
                  });
              </script>
          </body>
          </html>    \`;

              fs.writeFileSync(\`\${artwork.slug}.html\`, html);
          });
          
          console.log(\`\${artworksData.length} artwork pages generated!\`);
          EOF
          
          node build-site.js
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
